### PR TITLE
Updated readme file with correct link

### PR DESCRIPTION
**Pull request by anandprabhu**
- Update the readme file with correct link for `2. Naked Expressions` exercise

### CODE REVIEW

**Comment by anandprabhu** [comment]
Kindly review and merge @inancgumus

**Comment by anandprabhu** [comment]
@inancgumus yeah sure would update the PR

**Comment by inancgumus** [comment]
Hey @anandprabhu, sorry it was my mistake; I thought that you were updating a code file, whereas it was a markdown file, so your first PR was right.

Can you send it like so? + save the update that you made to README.md as well.

Sorry for the additional work.

**Comment by anandprabhu** [comment]
Hi @inancgumus no worries i have updated the PR with the update to exercise README.md file as well.

**Comment by inancgumus** [comment]
@anandprabhu Thanks :)

**Pull request merged**
